export const CHANGE_EXAMPLE = "CHANGE_EXAMPLE"
export const ACTIVE_LOADING = "ACTIVE_LOADING"
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS"
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE"
